### ISSUE TITLE
Upgrading to meteor 1.5.1 fails due to ddp-server constraint

### ISSUE THREAD

**Issue by goyan** [chatr/redpubsub#10]
please see below
regards,

> $ meteor update --release 1.5.1
> => Errors while initializing project:                                              
                                           
> While selecting package versions:
> error: Conflict: Constraint ddp-server@1.2.2 is not satisfied by ddp-server 2.0.0.
> Constraints on package "ddp-server":
> * ddp-server@2.0.0 <- top level
> * ddp-server@1.2.2 <- chatra:redpubsub 0.9.19

**Comment by sferoze** [comment]
I got this same error when trying to update today. But in the package.js file the ddp-server has no version constraint. How to solve this issue so we can upgrade Meteor?

@goyan

**Comment by artpolikarpov** [comment]
Oh, glad to know someone is using this package! Chatra still on 1.4.x in production, but I’ll try to solve this.

**Comment by sferoze** [comment]
@artpolikarpov yup recently started using this package. It is really amazing.. in how it connects non-persistent, horizontal scalable messages with mini-mongo. Pretty amazing! Meteor is for sure missing something like this in its default stack

**Comment by sferoze** [comment]
@artpolikarpov on atmosphere the version is 9.20 but on github the latest is 9.14

I wanted to copy the package into my packages folder so I could make the update that allows me to use Meteor 1.5.1

But I only have access to version 9.14 on github. Anyway you can update github to 9.20?

**Comment by artpolikarpov** [comment]
Just pushed the update. It should be fine.

**Comment by goyan** [comment]
thank you so much. updates fine.
