### ISSUE TITLE
would it be possible to monkey-match Meteor's mongo interface to use your system under the hood?

### ISSUE THREAD

**Issue by faceyspacey** [chatr/redpubsub#6]
I see that you created a new interface to perform mongo reads and writes--couldn't you just monkey patch Meteor to use your system instead. That way we developers don't have to change how they perform mongo calls?

**Comment by artpolikarpov** [comment]
That’s not possible. This package just simplifies building your custom message-bus-based solution. You have to now what channels to notify, what to listen, find those channels dynamically, what fields to fetch from DB, or skip fetching, or even skip DB.

This package is for deep optimisation, so some engineering work is required on your part.

If you don’t want (or not able) to do this work, you’re good to go along with [Livequery](https://www.meteor.com/livequery):

> Livequery drivers work magic by enabling these live queries [...] they will usually not be as performant as a custom-built message bus system, hand-tuned for your application's particular pattern of writes and queries. [...]
> 
> But though it is not as efficient as a custom solution, Livequery works today, instantly, with no engineering work required your part.

**Comment by artpolikarpov** [comment]
I close this because we’re not going to change the API’s. But we’re open for discussing. Thank you for you effort.
