### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by theodorDiaconu** [chatr/redpubsub#8]
Hello guys I believe this is an awesome package. We began working on something similar: https://github.com/cult-of-coders/redis-oplog without knowing there was work done in this direction. So we had to re-invent some stuff. However I looked through your code and I love it. Would you be interested in discussing more about this ?

**Comment by artpolikarpov** [comment]
@theodorDiaconu, oh sorry!

Missed out. Actually, I have looked through your code about 2-3 weeks ago. If you still interested, let's talk!
